/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Example */

#ifndef _Included_Example
#define _Included_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Example
 * Method:    initLSH
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Example_initLSH
  (JNIEnv *, jobject, jint);

/*
 * Class:     Example
 * Method:    addLSHPoint
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_Example_addLSHPoint
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     Example
 * Method:    updateLSHPoint
 * Signature: (I[I[I)V
 */
JNIEXPORT void JNICALL Java_Example_updateLSHPoint
  (JNIEnv *, jobject, jint, jintArray, jintArray);

/*
 * Class:     Example
 * Method:    getRecommendedItems
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_Example_getRecommendedItems
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
